<!--/////////////////////////////////////////////////////
//CMS Downloader mit Unterstützung von:	  	          //
//Unziper 0.0.2 Alpha von Andreas Tasch				  //
//****************************************************//
//Urheber: Alexander Pascual                          //
//Kontakt: alex-pascual@hotmail.com                   //
//Version 1.0 (Last Update 13.08.2015)                //
//Copyright (c): Dieses Script darf unter Angabe      //
//des Urhebers verwendet werden und ist ausdrücklich  //
//erwünscht.                                          //
/////////////////////////////////////////////////////-->

<head>
  <title>CMS Installer</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <style type="text/css">
    <!--
    body {
      font-family: Arial, serif;
      line-height: 150%;
    }
    fieldset {
      border: 0px solid #000;
    }
    .status {
      margin-top: 20px;
      padding: 5px;
      font-size: 80%;
      background: #EEE;
      border: 1px dotted #DDD;
    }
    .submit {
      -moz-box-shadow: inset 0px 1px 0px 0px #bbdaf7;
      -webkit-box-shadow: inset 0px 1px 0px 0px #bbdaf7;
      box-shadow: inset 0px 1px 0px 0px #bbdaf7;
      background: -webkit-gradient(linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5));
      background: -moz-linear-gradient(center top, #79bbff 5%, #378de5 100%);
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
      background-color: #79bbff;
      -moz-border-radius: 4px;
      -webkit-border-radius: 4px;
      border-radius: 4px;
      border: 1px solid #84bbf3;
      display: inline-block;
      color: #ffffff;
      font-family: arial;
      font-size: 15px;
      font-weight: bold;
      padding: 10px 24px;
      text-decoration: none;
      text-shadow: 1px 1px 0px #528ecc;
    }
    .submit:hover {
      background: -webkit-gradient(linear, left top, left bottom, color-stop(0.05, #378de5), color-stop(1, #79bbff));
      background: -moz-linear-gradient(center top, #378de5 5%, #79bbff 100%);
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#378de5', endColorstr='#79bbff');
      background-color: #378de5;
    }
    .submit:active {
      position: relative;
      top: 1px;
    }
    /* This imageless css button was generated by CSSButtonGenerator.com */
    .style1 {
	font-size: xx-small;
}
    .style2 {
    font-size: small;
	color: #008000;
  }
    .style3 {
    font-size: small;
  	color: #FF0000;
  }
    -->
  </style>
</head>

<body>
<h1>CMS Installer<br><span class="style1">Bereitgestellt von 
<a href="http://my-update.com">www.my-update.com</a></span></h1>

<p>Mit diesem CMS Installer können Sie ganz leicht die nachstehenden CMS Systeme installieren!</p>
<p>Voraussetzung zur Installation:</p>
</body>

<?php if (phpversion()> '5.6') {
echo '<p class="style2"><strong>Es wird eine unterstützte PHP Version verwendet: ( ' . phpversion() . ' )</strong></p>';
} else {
echo '<p class="style3"><strong>Es wird PHP 5.6+ benötigt. Sie Verwenden: ( ' . phpversion() . ' )</strong></p>';
exit;
}
?>
<?php if (phpversion('zip')> '0') {
echo '<p class="style2"><strong>Die PHP Erweiterung "ZIP" ist aktiv</strong></p>';
} else {
echo '<p class="style3"><strong>Die PHP Erweiterung "ZIP" ist deaktiviert</strong></p>';
exit;
}
?>

<hr>

<?php
$fck = $_POST['fck'];
if ($fck != "1") {
	echo
	'<table style="width: 900px">
	<tr>
		<td>
			<form action="" method="post">
			<a href="http://www.joomla.ch/"><img src="https://www.green.ch/Portals/0/Helpdesk/Hosting/cms_installer/script/joomla-logo-300.jpg"/></a>
			<br>
			<input name="cms_url" type="hidden" value="https://www.green.ch/Portals/0/Helpdesk/Hosting/cms_installer/script/joomla_DE.zip" />
			<input name="fck" type="hidden" value="1" />
			<input name="Submit1" type="submit" class="submit" value="Ich möchte Joomla installieren" style="width: 300px" />
			</form>
		</td>
		<td>
		</td>
		<td>
			<h2>Joomla! - CMS für Millionen von Websites</h2>
			<p>Joomla! ist ein preisgekröntes Open Source Content Management System (CMS) mit dem sich professionelle Internetprojekte realisieren lassen. Dazu braucht es keine Kenntnisse in Programmiersprachen oder spezielle Software zum Bearbeiten.</p>
		</td>	
	</tr>
	<tr>
		<td>
			<form action="" method="post">
			<a href="https://de.wordpress.org/"><img src="https://www.green.ch/Portals/0/Helpdesk/Hosting/cms_installer/script/wordpress-logo-300.jpg"/></a>
			<br>
			<input name="cms_url" type="hidden" value="https://www.green.ch/Portals/0/Helpdesk/Hosting/cms_installer/script/wordpress_DE.zip" />
			<input name="fck" type="hidden" value="1" />
			<input name="Submit1" type="submit" class="submit" value="Ich möchte Wordpress installieren" style="width: 300px" />
			</form></td>
		</td>
		<td>
		</td>
		<td>
		<h2>WordPress - Das Optimale CMS für Ihren Blog</h2>
		<p>WordPress ist eine Web-Software, mit der Sie moderne Internetpräsenzen, Websites, Blogs und Online-Shops umsetzen können. WordPress ist Freie Software, die Sie kostenlos nutzen und erweitern dürfen.</p>
		</td>
	</tr>
	</table>';
	exit;
}
//**Download via CURL**//

$url = $_POST['cms_url'];
$zipFile = "cms.zip"; // Pfad zur .zip Datei auf dem Server
$zipResource = fopen($zipFile, "w");

// Lädt die Datei herunter
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_FAILONERROR, true);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_AUTOREFERER, true);
curl_setopt($ch, CURLOPT_BINARYTRANSFER,true);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0); 
curl_setopt($ch, CURLOPT_FILE, $zipResource);
$page = curl_exec($ch);
if(!$page) {
 echo "Error :- ".curl_error($ch);
}
curl_close($ch);

?>
<?php
/**
 * The Unzipper extracts .zip archives and .gz files on webservers. It's handy if you
 * do not have shell access. E.g. if you want to upload a lot of files
 * (php framework or image collection) as archive to save time.
 *
 *
 * @author  Andreas Tasch, at[tec], attec.at
 * @license GNU GPL v3
 * @package attec.toolbox
 * @version 0.0.2 Alpha
 */
$timestart = microtime(TRUE);
$arc = new Unzipper;
$timeend = microtime(TRUE);
$time = $timeend - $timestart;
class Unzipper {
  public $localdir = '.';
  public $zipfiles = array();
  public static $status = '';
  public function __construct() {
    //read directory and pick .zip and .gz files
    if ($dh = opendir($this->localdir)) {
      while (($file = readdir($dh)) !== FALSE) {
        if (pathinfo($file, PATHINFO_EXTENSION) === 'zip'
          || pathinfo($file, PATHINFO_EXTENSION) === 'gz'
        ) {
          $this->zipfiles[] = $file;
        }
      }
      closedir($dh);
      if(!empty($this->zipfiles)) {
        self::$status = '.zip or .gz files found, ready for extraction';
      }
      else {
        self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Error: No .zip or .gz files found.</span>';
      }
    }
    //check if an archive was selected for unzipping
    //check if archive has been selected
    $input = '';
    $input = strip_tags('cms.zip'); // Dies definiert das zu Entpakende File. Kann durch Variable ersetzt werden.
    //allow only local existing archives to extract
    if ($input !== '') {
      if (in_array($input, $this->zipfiles)) {
        self::extract($input, $this->localdir);
      }
    }
  }
  public static function extract($archive, $destination) {
    $ext = pathinfo($archive, PATHINFO_EXTENSION);
    if ($ext === 'zip') {
      self::extractZipArchive($archive, $destination);
    }
    else {
      if ($ext === 'gz') {
        self::extractGzipFile($archive, $destination);
      }
    }
  }
  /**
   * Dieser Teil entpackt eine .zip Datei
   *
   * @param $archive
   * @param $destination
   */
  public static function extractZipArchive($archive, $destination) {
    // Check if webserver supports unzipping.
    if(!class_exists('ZipArchive')) {
      self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Error: Your PHP version does not support unzip functionality.</span>';
      return;
    }
    $zip = new ZipArchive;
    // Check if archive is readable.
    if ($zip->open($archive) === TRUE) {
      // Check if destination is writable
      if(is_writeable($destination . '/')) {
        $zip->extractTo($destination);
        $zip->close();
        self::$status = '<span style="color:green; font-weight:bold;font-size:120%;">Download und Entpacken erfolgreich!</span>';
      }
      else {
        self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Error: Keine Schreibrechte auf dem Webverzeichnis</span>';
      }
    }
    else {
      self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Error: Das .zip Archiv ist beschädigt und kann nicht entpackt werden</span>';
    }
  }
  /**
   * Dieser Teil entpackt eine .gz Datei.
   *
   * @param $archive
   * @param $destination
   */
  public static function extractGzipFile($archive, $destination) {
    // Check if zlib is enabled
    if(!function_exists('gzopen')) {
      self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Error: Your PHP has no zlib support enabled.</span>';
      return;
    }
    $filename = pathinfo($archive, PATHINFO_FILENAME);
    $gzipped = gzopen($archive, "rb");
    $file = fopen($filename, "w");
    while ($string = gzread($gzipped, 4096)) {
      fwrite($file, $string, strlen($string));
    }
    gzclose($gzipped);
    fclose($file);
    // Check if file was extracted.
    if(file_exists($destination . '/' . $filename)) {
      self::$status = '<span style="color:green; font-weight:bold;font-size:120%;">Download und Entpacken erfolgreich</span>';
    }
    else {
      self::$status = '<span style="color:red; font-weight:bold;font-size:120%;">Fehler: Entpacken fehlgeschlagen</span>';
    }
  }
}
?>
<body>

<p class="status">
  Status: <?php echo $arc::$status; ?>
  <br/>
  Prozesszeit: <?php echo $time; ?> ms
  <?php unlink('cms.zip'); ?> <!--Löscht die ZIP Datei nach dem Entpacken-->
  <?php unlink('install.php'); ?> <!--Löscht die install.php Datei nach dem Entpacken-->
<form action="index.php">
    <input type="submit" class="submit" value="CMS Installation fortsetzen">
</form>
</body>